#include "Cercle.h"




double Cercle::CalculerSurface(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D5E begin
{
    return 0.0;
}
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D5E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Cercle::CalculerPerimetre(double diametre)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D60 begin
{
    return 0.0;
}
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D60 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
