#include "Ex1.h"




int Ex1::main()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D2B begin
{
    return 0;
}
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D2B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Ex1::ChoisirForme()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D2D begin
{
    return 0;
}
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D2D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::SaisirParametres(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D2F begin
{
    
}
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D2F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::AfficherResultats(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D31 begin
{
    
}
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D31 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ex1::ExecuterLesCalculs(int CodeForme)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D33 begin
{
    
}
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D33 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
