#include "FormesGeometriques.h"




double FormesGeometriques::CalculerSurface(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D3C begin
{
    return 0.0;
}
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D3C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::CalculerPerimetre(double x1, double x2)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D42 begin
{
    return 0.0;
}
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D42 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetSurface()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D45 begin
{
    return 0.0;
}
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D45 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double FormesGeometriques::GetPerimetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D47 begin
{
    return 0.0;
}
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D47 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
