#include "Rectangle.h"




double Rectangle::CalculerSurface(double largeur, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D57 begin
{
    return 0.0;
}
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D57 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Rectangle::CalculerPerimetre(double largeur, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D5A begin
{
    return 0.0;
}
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D5A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
