#include "TriangleRectangle.h"




TriangleRectangle::CalculerSurface(double base, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D4D begin
{
}
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D4D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

TriangleRectangle::CalculerPerimetre(double base, double hauteur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D50 begin
{
}
// section 10--28--98-76-57d22251:1931a7d3dbc:-8000:0000000000000D50 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
